# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install @angular-devkit/build-angular
    npm install
    ng build --prod
  displayName: 'npm install and build'

# - task: CmdLine@2
#   inputs:
#     script: 'node node_modules\protractor\bin\webdriver-manager update'
#  displayName: 'Update webdriver'

- script: |
    npm install -g @angular/cli
    npm install @angular-devkit/build-angular
    npm install
    ng ng test --watch=false --reporters junit,dots --browsers ChromeHeadless --code-coverage
  displayName: 'Karma test'


# Publish Test Results
# Publish test results to Azure Pipelines
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit, cTest
    testResultsFiles: '**/TEST-*.xml' 
    #searchFolder: '$(System.DefaultWorkingDirectory)' # Optional
    #mergeTestResults: false # Optional
    #failTaskOnFailedTests: false # Optional
    #testRunTitle: # Optional
    #buildPlatform: # Optional
    #buildConfiguration: # Optional
    #publishRunAttachments: true # Optional

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist'
    ArtifactName: 'zeg-studio'
    publishLocation: 'Container'
  displayName: 'Publish artifact: Zeg Studio'
